# Encoding

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("loan_defaulter_cleaned.csv")

In [5]:
df.head()

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Education_Level,Housing_Status,Default
0,59,52154.0,11276,823,15,Bachelors,Own,0
1,49,116646.0,43663,315,5,PhD,Own,0
2,35,61157.0,18994,428,8,Masters,Own,1
3,63,52154.0,28499,408,26,Bachelors,Rent,0
4,28,148876.0,28040,832,3,Masters,Own,1

In [6]:
df_cat_clm = df.select_dtypes(include=['object'])

In [7]:
df_cat_clm.columns

Index(['Education_Level', 'Housing_Status'], dtype='object')

In [8]:
df['Education_Level'].unique()

array(['Bachelors', 'PhD', 'Masters', 'High School'], dtype=object)

In [9]:
df['Education_Level'].value_counts()

Education_Level
PhD            260
Masters        253
Bachelors      248
High School    239
Name: count, dtype: int64

In [13]:
education_mapping = {
    "High School" : 0,
    "Bachelors" : 1,
    "Masters" : 2,
    "PhD" : 3
}

In [14]:
df['Education_Level'] = df['Education_Level'].map(education_mapping)

In [15]:
df['Education_Level']

0      1
1      3
2      2
3      1
4      2
      ..
995    3
996    0
997    2
998    3
999    0
Name: Education_Level, Length: 1000, dtype: int64

In [10]:
df['Housing_Status'].unique()

array(['Own', 'Rent', 'Mortgage'], dtype=object)

In [12]:
df['Housing_Status'].value_counts()

Housing_Status
Mortgage    349
Own         330
Rent        321
Name: count, dtype: int64

In [16]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
encoder = OneHotEncoder(drop='first',sparse_output=False)
#drop avoids the dummy variable
#sparse_output returnns a numpy array

In [20]:
encoded_data = encoder.fit_transform(df[['Housing_Status']])

In [21]:
encoded_columns = encoder.get_feature_names_out(['Housing_Status'])

In [22]:
encoded_df = pd.DataFrame(encoded_data,columns=encoded_columns,index= df.index)

In [23]:
df = df.drop(columns=['Housing_Status'])

In [24]:
df = pd.concat([df,encoded_df],axis = 1)

In [25]:
df.head()

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Education_Level,Default,Housing_Status_Own,Housing_Status_Rent
0,59,52154.0,11276,823,15,1,0,1.0,0.0
1,49,116646.0,43663,315,5,3,0,1.0,0.0
2,35,61157.0,18994,428,8,2,1,1.0,0.0
3,63,52154.0,28499,408,26,1,0,0.0,1.0
4,28,148876.0,28040,832,3,2,1,1.0,0.0

In [26]:
df.to_csv("loan_defaulter_encoded.csv",index=False)